version: "2.4"

services:

  postgres:
    image: postgres
    hostname: postgres
    restart: always
    extends:
      file: ../common/config-tz.yml
      service: config
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
      - ./config/postgresql.conf:/etc/postgresql/postgresql.conf
    environment:
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
    command: ["postgres", "-c", "log_min_messages=${POSTGRES_LOG_MIN_MESSAGES}"]
    networks:
      - keycloak

  postgres-admin:
    image: dpage/pgadmin4
    hostname: postgres-admin
    restart: always
    extends:
      file: ../common/config-tz.yml
      service: config
    ports:
      - ${POSTGRES_DB_ADMIN_PORT}:${POSTGRES_DB_ADMIN_PORT}
    environment:
      - PGADMIN_LISTEN_PORT=${POSTGRES_DB_ADMIN_PORT}
      - PGADMIN_DEFAULT_EMAIL=${POSTGRES_DB_ADMIN_PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${POSTGRES_DB_ADMIN_PGADMIN_DEFAULT_PASSWORD}
    networks:
      - keycloak


  postgres-backup:
    image: postgres
    hostname: postgres-backup
    extends:
      file: ../common/config-tz.yml
      service: config
    networks:
      - keycloak
    volumes:
      - ${KEYCLOAK_BACKUP_PATH}:/dump
#      - /etc/localtime:/etc/localtime:ro
    environment:
      - PGHOST=keycloak-db
      - PGUSER=${DB_USER}
      - PGPASSWORD=${DB_PASSWORD}
      - BACKUP_NUM_KEEP=7
      - BACKUP_FREQUENCY=1d
    entrypoint: |
      bash -c 'bash -s <<EOF
      trap "break;exit" SIGHUP SIGINT SIGTERM
      sleep 2m
      while /bin/true; do
        pg_dump -Fc > /dump/dump_\`date +%d-%m-%Y"_"%H_%M_%S\`.psql
        (ls -t /dump/dump*.psql|head -n $$BACKUP_NUM_KEEP;ls /dump/dump*.psql)|sort|uniq -u|xargs rm -- {}
        sleep $$BACKUP_FREQUENCY
      done
      EOF'



networks:
  keycloak:
  traefik:
  internal:
