version: "3.8"

services:


  keycloak:
  #   image: quay.io/keycloak/keycloak:latest
    image: jboss/keycloak
    hostname: keycloak
    domainname: "${DOMAIN_NAME}"
    depends_on:
      - "postgres"
    ports:
      - ${KEYCLOAK_PORT}:9990
    volumes:
      - ${KEYCLOAK_CUSTOM_THEME_PATH}:/opt/jboss/keycloak/themes/customtheme
    environment:
      - TZ=${GLOBAL_TZ}
      - PUID=1000
      - PGID=1000
      - KEYCLOAK_LOGLEVEL=${KEYCLOAK_LOGLEVEL}
      # https://geek-cookbook.funkypenguin.co.nz/recipes/keycloak/setup-oidc-provider/
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      # - KEYCLOAK_IMPORT=/config.json
      - DB_VENDOR=${KEYCLOAK_DB_VENDOR}
      - DB_DATABASE=${KEYCLOAK_DB_DATABASE}
      - DB_ADDR=${KEYCLOAK_DB_ADDR}
      - DB_USER=${POSTGRES_DB_USER}
      - DB_PASSWORD=${POSTGRES_DB_PASSWORD}
      - DB_PORT=${POSTGRES_PORT}
      # This is required to run keycloak behind traefik
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HOSTNAME=${KEYCLOAK_SUBDOMAIN_NAME}.${DOMAIN_NAME}
      # Tell Postgress what user/password to create
      - POSTGRES_USER=${POSTGRES_DB_USER}
      - POSTGRES_PASSWORD=${POSTGRES_DB_PASSWORD}
      - KEYCLOAK_WELCOME_THEME=${KEYCLOAK_WELCOME_THEME}
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      - "traefik.backend=traefik"
      # Define the URL to access this app
      - "traefik.http.routers.keycloak.rule=Host(`${KEYCLOAK_SUBDOMAIN_NAME}.${DOMAIN_NAME}`)"
      # Access via HTTPS only
      - "traefik.http.routers.keycloak.entrypoints=websecure"
      # The application (i.e. this container)
      - "traefik.http.routers.keycloak.service=keycloak"
      # Select middleware chain https-only and keycloakforwardauth
      #- "traefik.http.routers.keycloak.middlewares=keycloakForwardAuth"
      #- "traefik.http.routers.keycloak.middlewares=secured"
      - "traefik.http.services.keycloak.loadbalancer.server.port=${KEYCLOAK_PORT}"
      # TLS is used to protect the domain
      - "traefik.http.routers.keycloak.tls=true"
      - "traefik.http.routers.keycloak.tls.certresolver=leresolver"
      - "traefik.http.routers.keycloak.tls.domains[0].main=${DOMAIN_NAME}"
      - "traefik.http.routers.keycloak.tls.domains[0].sans=*.${DOMAIN_NAME}"
    networks:
      - internal

networks:
  internal:
