version: "3.8"

services:


  keycloak:
  #   image: quay.io/keycloak/keycloak:latest
    image: jboss/keycloak
    hostname: keycloak
    domainname: "${DOMAIN_NAME}"
    depends_on:
      - "postgres"
    # ports:
    #   - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT_INTERNAL}
    #   - ${KEYCLOAK_PORT_MANAGMENT}:${KEYCLOAK_PORT_MANAGMENT_INTERNAL}
    volumes:
      - ${KEYCLOAK_CUSTOM_THEME_PATH}:/opt/jboss/keycloak/themes/customtheme
    environment:
      - TZ=${GLOBAL_TZ}
      - PUID=1000
      - PGID=1000
      - KEYCLOAK_LOGLEVEL=${KEYCLOAK_LOGLEVEL}
      # https://geek-cookbook.funkypenguin.co.nz/recipes/keycloak/setup-oidc-provider/
      - KEYCLOAK_USER=${KEYCLOAK_USER}
      - KEYCLOAK_PASSWORD=${KEYCLOAK_PASSWORD}
      # - KEYCLOAK_IMPORT=/config.json
      - DB_VENDOR=${KEYCLOAK_DB_VENDOR}
      - DB_DATABASE=${KEYCLOAK_DB_DATABASE}
      - DB_ADDR=${KEYCLOAK_DB_ADDR}
      - DB_USER=${KEYCLOAK_DB_USER}
      - DB_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - DB_PORT=${KEYCLOAK_DB_PORT}
      # This is required to run keycloak behind traefik
      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_HOSTNAME=${KEYCLOAK_SUBDOMAIN_NAME}.${DOMAIN_NAME}
      # Tell Postgress what user/password to create
      - POSTGRES_USER=${KEYCLOAK_DB_USER}
      - POSTGRES_PASSWORD=${KEYCLOAK_DB_PASSWORD}
      - KEYCLOAK_WELCOME_THEME=${KEYCLOAK_WELCOME_THEME}
    command: ["${KEYCLOAK_COMMAND}"]
    labels:
      traefik.frontend.priority: 1
      traefik.enable: true
      traefik.port: ${KEYCLOAK_PORT}
      # traefik.http.routers.keycloak.service: keycloak
      # traefik.http.routers.keycloak.rule: "Host(`${KEYCLOAK_SUBDOMAIN_NAME}.${DOMAIN_NAME}`)"
      # traefik.http.routers.keycloak.entrypoints: web
      traefik.http.routers.keycloak_https.rule: "Host(`${KEYCLOAK_SUBDOMAIN_NAME}.${DOMAIN_NAME}`)"
      traefik.http.routers.keycloak_https.tls: true
      traefik.http.routers.keycloak_https.entrypoints: websecure
      traefik.http.routers.keycloak_https.service: keycloak
      traefik.http.services.keycloak.loadbalancer.passHostHeader: true
      traefik.http.services.keycloak.loadbalancer.server.port: ${KEYCLOAK_PORT}
      # Select middleware chain https-only and traefik-forward-auth
      #- "traefik.http.routers.keycloak.middlewares=traefik-forward-auth"
      #- "traefik.http.routers.keycloak.middlewares=secured"
      # TLS is used to protect the domain
      # - "traefik.http.routers.keycloak.tls=true"
      # - "traefik.http.routers.keycloak.tls.certresolver=leresolver"
      # - "traefik.http.routers.keycloak.tls.domains[0].main=${DOMAIN_NAME}"
      # - "traefik.http.routers.keycloak.tls.domains[0].sans=*.${DOMAIN_NAME}"
    networks:
      internal:
        aliases:
          - ${KEYCLOAK_SUBDOMAIN_NAME}
          - ${KEYCLOAK_SUBDOMAIN_NAME}.${DOMAIN_NAME}

networks:
  internal:
