version: "3.8"

services:

  traefik:
    image: traefik
    security_opt:
      - no-new-privileges:true
    restart: "always"
    volumes:
      - ${TRAEFIK_DOCKER_SOCK}:/var/run/docker.sock:ro
      - ${TRAEFIK_CERTIFICATE_PATH}:/letsencrypt
      - ${TRAEFIK_CONFIG_DYNAMIC_PATH}:/etc/traefik/dynamic_conf
    ports:
      - ${TRAEFIK_HTTP_PORT}:${TRAEFIK_HTTP_PORT}
      - ${TRAEFIK_HTTPS_PORT}:${TRAEFIK_HTTPS_PORT}
      - ${TRAEFIK_API_PORT}:${TRAEFIK_API_PORT}
    command:
      - "--log.level=${TRAEFIK_LOG_LEVEL}"
      - "--accesslog=${TRAEFIK_ACCESS_LOG}"
      - "--api.insecure=true" # Don't do that in production!
      - "--api.dashboard=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--global.sendAnonymousUsage=true"

      # Entrypoints for HTTP, HTTPS, and NX (TCP + UDP)
      - "--entrypoints.web.address=:${TRAEFIK_HTTP_PORT}"
      - "--entrypoints.websecure.address=:${TRAEFIK_HTTPS_PORT}"
      - "--entrypoints.traefik.address=:${TRAEFIK_API_PORT}"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      # - "--entrypoints.web.http.redirections.entryPoint.permanent=true"

      # Manual keys
      - "--providers.file.directory=/etc/traefik/dynamic_conf"
      - "--providers.file.watch=true"
    labels:
      traefik.frontend.priority: 1
      traefik.enable: true
      traefik.http.routers.traefik.rule: "Host(`${TRAEFIK_SUBDOMAIN_NAME}.${DOMAIN_NAME}`)"
      traefik.http.routers.traefik.service: api@internal
      traefik.http.services.api.loadbalancer.passHostHeader: true


      # # Global Redirect HTTP to HTTPS
      # traefik.http.routers.http-catchall.rule: "hostregexp(`{host:.+}`)"
      # traefik.http.routers.http-catchall.entrypoints: websecure
      # traefik.http.routers.http-catchall.middlewares: redirect-to-https
      # traefik.http.middlewares.redirect-to-https.redirectscheme.scheme: https
      # traefik.http.middlewares.redirect-to-https.redirectscheme.permanent: true
    environment:
      - TZ=${GLOBAL_TZ}

    networks:
      internal:
        aliases:
          - ${TRAEFIK_SUBDOMAIN_NAME}
          - ${TRAEFIK_SUBDOMAIN_NAME}.${DOMAIN_NAME}

  # will only do this when files are not there
  createcert:
    image: brunopadz/mkcert-docker
    working_dir: /root/.local/share/mkcert
    command:
      - /bin/sh
      - -c
      - "test ! -f mkcert.key && mkcert -install && mkcert -key-file mkcert.key -cert-file mkcert.pem -client ${TRAEFIK_CERT_DOMAINS}"
    volumes:
      - ${TRAEFIK_CERTIFICATE_PATH}:/root/.local/share/mkcert
    environment:
      - TZ=${GLOBAL_TZ}

  # will only do this when files are not there
  createcertpkcs12:
    image: frapsoft/openssl
    working_dir: /export
    entrypoint: ""
    command:
      - /bin/ash
      - -c
      - "test ! -f mkcert.pfx && openssl pkcs12 -export -out mkcert.pfx -in mkcert.pem -inkey mkcert.key -certfile rootCA.pem -passout pass:${TRAEFIK_CERT_KEYPASS}"
    volumes:
      - ${TRAEFIK_CERTIFICATE_PATH}:/export
    environment:
      - TZ=${GLOBAL_TZ}

networks:
  internal:

