version: "3.8"

services:

  nginx:
    image: nginx
    restart: always
    working_dir: /content
    hostname: "nginx"
    labels:
      - "traefik.frontend.priority=1"
      - "traefik.enable=true"
      - "traefik.http.routers.nginx.rule=PathPrefix(`/`)"
      - "traefik.http.routers.nginx.entrypoints=web"
      - "traefik.http.routers.nginx_https.rule=PathPrefix(`/`)"
      - "traefik.http.routers.nginx_https.tls=true"
      - "traefik.http.routers.nginx_https.entrypoints=websecure"
    volumes:
      - ${NGINX_CONTENT_PATH}:/content
      - ${NGINX_CONFIG_FILE}:/etc/nginx/nginx.conf
    environment:
      - TZ=${GLOBAL_TZ}
    networks:
      - internal

networks:
  internal:
